server:
  port: 80

spring:
  application:
    name: cloud-consumer-hystrix-order80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: consume-order80
